# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TensorFlowLite_model_test' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for TensorFlowLite_model_test with specific commit IDs
  # All Firebase pods come from the same repository
  pod 'Firebase/Core', '6.3.0'
  pod 'Firebase/MLModelInterpreter', '6.3.0'
  pod 'Firebase/Analytics', '6.3.0'
  pod 'Firebase/Performance', '6.3.0'
end
